#include "view_manager_qt_component.h"

#include <QApplication>
#include <QDockWidget>
#include <QMainWindow>
#include <QTabBar>
#include <QTabWidget>
#include <QToolButton>

#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include <memory>
#include <optional>
#include <string>
#include <vector>

using testing::ElementsAre;

namespace {

ViewManagerQtComponent::ViewInfo MakeView(ViewManagerQtComponent::ViewId id,
                                          QWidget& widget,
                                          std::u16string title,
                                          bool dock = false) {
  return {
      .id = id,
      .widget = &widget,
      .title = std::move(title),
      .state_name = "view_" + std::to_string(id),
      .dock = dock,
  };
}

}  // namespace

TEST(ViewManagerQtComponentTest, AddSplitSaveAndRemovePlainWidgets) {
  QMainWindow main_window;
  ViewManagerQtComponent component{main_window};

  auto widget1 = std::make_unique<QWidget>();
  auto widget2 = std::make_unique<QWidget>();

  std::vector<ViewManagerQtComponent::ViewInfo> views{
      MakeView(1, *widget1, u"One"),
      MakeView(2, *widget2, u"Two"),
  };

  component.AddView(views[0], std::nullopt);
  component.AddView(views[1], views[0].id);
  component.SplitView(views[1].id, /*vertically=*/false);

  auto layout = component.SaveLayout(views);
  EXPECT_EQ(layout.main.type, ViewManagerQtComponent::LayoutNode::Type::Split);
  EXPECT_TRUE(layout.main.split_vertical);
  ASSERT_TRUE(layout.main.left);
  ASSERT_TRUE(layout.main.right);
  EXPECT_THAT(layout.main.left->tabs, ElementsAre(views[0].id));
  EXPECT_THAT(layout.main.right->tabs, ElementsAre(views[1].id));

  ASSERT_TRUE(component.RemoveView(views[0].id));
  ASSERT_TRUE(component.RemoveView(views[1].id));
  widget1->setParent(nullptr);
  widget2->setParent(nullptr);
}

TEST(ViewManagerQtComponentTest, OpenLayoutRestoresSplitTabs) {
  QMainWindow main_window;
  ViewManagerQtComponent component{main_window};

  auto widget1 = std::make_unique<QWidget>();
  auto widget2 = std::make_unique<QWidget>();

  std::vector<ViewManagerQtComponent::ViewInfo> views{
      MakeView(1, *widget1, u"One"),
      MakeView(2, *widget2, u"Two"),
  };

  ViewManagerQtComponent::SavedLayout layout;
  layout.main.type = ViewManagerQtComponent::LayoutNode::Type::Split;
  layout.main.split_vertical = false;
  layout.main.split_pos = 25;
  layout.main.left = std::make_unique<ViewManagerQtComponent::LayoutNode>();
  layout.main.left->tabs = {views[0].id};
  layout.main.right = std::make_unique<ViewManagerQtComponent::LayoutNode>();
  layout.main.right->tabs = {views[1].id};

  component.OpenLayout(views, layout);

  auto saved_layout = component.SaveLayout(views);
  EXPECT_EQ(saved_layout.main.type,
            ViewManagerQtComponent::LayoutNode::Type::Split);
  EXPECT_FALSE(saved_layout.main.split_vertical);
  ASSERT_TRUE(saved_layout.main.left);
  ASSERT_TRUE(saved_layout.main.right);
  EXPECT_THAT(saved_layout.main.left->tabs, ElementsAre(views[0].id));
  EXPECT_THAT(saved_layout.main.right->tabs, ElementsAre(views[1].id));

  ASSERT_TRUE(component.RemoveView(views[0].id));
  ASSERT_TRUE(component.RemoveView(views[1].id));
  widget1->setParent(nullptr);
  widget2->setParent(nullptr);
}

TEST(ViewManagerQtComponentTest, SetViewTitleUpdatesTabAndDockTitles) {
  QMainWindow main_window;
  ViewManagerQtComponent component{main_window};

  auto tab_widget = std::make_unique<QWidget>();
  auto* dock_widget = new QWidget;

  auto tab_view = MakeView(1, *tab_widget, u"Tab");
  auto dock_view = MakeView(2, *dock_widget, u"Dock", /*dock=*/true);

  component.AddView(tab_view, std::nullopt);
  component.AddView(dock_view, std::nullopt);

  component.SetViewTitle(tab_view.id, u"New Tab");
  component.SetViewTitle(dock_view.id, u"New Dock");

  auto* tabs = main_window.findChild<DockTabWidget*>();
  ASSERT_NE(tabs, nullptr);
  ASSERT_EQ(tabs->count(), 1);
  EXPECT_EQ(tabs->tabText(0), "New Tab");

  auto docks = main_window.findChildren<QDockWidget*>();
  ASSERT_EQ(docks.size(), 1);
  EXPECT_EQ(docks[0]->windowTitle(), "New Dock");

  ASSERT_TRUE(component.RemoveView(tab_view.id));
  tab_widget->setParent(nullptr);
}

TEST(ViewManagerQtComponentTest, DockCloseInvokesCloseHandler) {
  QMainWindow main_window;
  ViewManagerQtComponent component{main_window};

  auto* widget = new QWidget;
  auto view = MakeView(1, *widget, u"Dock", /*dock=*/true);

  std::vector<ViewManagerQtComponent::ViewId> closed_views;
  component.SetCloseViewHandler([&](ViewManagerQtComponent::ViewId view_id) {
    closed_views.emplace_back(view_id);
  });

  component.AddView(view, std::nullopt);

  auto docks = main_window.findChildren<QDockWidget*>();
  ASSERT_EQ(docks.size(), 1);

  docks[0]->close();
  QApplication::processEvents();

  EXPECT_THAT(closed_views, ElementsAre(view.id));
}

// Tabified docks share one QTabBar generated by the QMainWindow. Activating a
// docked view has to select its tab there — GetTabWidget only finds the central
// area's DockTabWidget, so without an explicit raise() the second pane stayed
// on top and the caller's choice was silently ignored.
TEST(ViewManagerQtComponentTest, ActivateViewRaisesATabifiedDock) {
  QMainWindow main_window;
  ViewManagerQtComponent component{main_window};

  auto* first_widget = new QWidget;
  auto* second_widget = new QWidget;
  auto first = MakeView(1, *first_widget, u"First", /*dock=*/true);
  auto second = MakeView(2, *second_widget, u"Second", /*dock=*/true);

  component.AddView(first, std::nullopt);
  component.AddView(second, std::nullopt);

  auto docks = main_window.findChildren<QDockWidget*>();
  ASSERT_EQ(docks.size(), 2);

  auto tab_bars = main_window.findChildren<QTabBar*>();
  ASSERT_EQ(tab_bars.size(), 1) << "the two docks should be tabified together";
  QTabBar* tab_bar = tab_bars[0];

  // Adding the second dock leaves it selected.
  ASSERT_EQ(tab_bar->tabText(tab_bar->currentIndex()), "Second");

  component.ActivateView(first.id);
  QApplication::processEvents();

  EXPECT_EQ(tab_bar->tabText(tab_bar->currentIndex()), "First");
}

// The pre-existing tab path must keep working — the dock branch is an else,
// so a regression there would be invisible to the dock test above.
TEST(ViewManagerQtComponentTest, ActivateViewSelectsTheTabOfANonDockedView) {
  QMainWindow main_window;
  ViewManagerQtComponent component{main_window};

  auto* first_widget = new QWidget;
  auto* second_widget = new QWidget;
  auto first = MakeView(1, *first_widget, u"First");
  auto second = MakeView(2, *second_widget, u"Second");

  component.AddView(first, std::nullopt);
  component.AddView(second, std::nullopt);

  auto tabs = main_window.findChildren<QTabWidget*>();
  ASSERT_EQ(tabs.size(), 1);

  component.ActivateView(second.id);
  QApplication::processEvents();
  EXPECT_EQ(tabs[0]->currentWidget(), second_widget);

  component.ActivateView(first.id);
  QApplication::processEvents();
  EXPECT_EQ(tabs[0]->currentWidget(), first_widget);
}

// The "new view" button on the tab strip. Drawn only when the host wants one:
// an unwired `+` would offer an action nothing performs, which is worse than
// offering nothing.
TEST(ViewManagerQtComponentTest, NoNewViewButtonWithoutAHandler) {
  QMainWindow main_window;
  ViewManagerQtComponent component{main_window};

  auto* widget = new QWidget;
  auto view = MakeView(1, *widget, u"One");
  component.AddView(view, std::nullopt);

  auto tabs = main_window.findChildren<QTabWidget*>();
  ASSERT_EQ(tabs.size(), 1);
  EXPECT_EQ(tabs[0]->cornerWidget(Qt::TopRightCorner), nullptr);
}

TEST(ViewManagerQtComponentTest, NewViewButtonCallsTheHandlerWhereItSits) {
  QMainWindow main_window;
  ViewManagerQtComponent component{main_window};

  std::vector<QPoint> points;
  component.SetNewTabHandler(
      [&](const QPoint& point) { points.emplace_back(point); });

  auto* widget = new QWidget;
  auto view = MakeView(1, *widget, u"One");
  component.AddView(view, std::nullopt);

  auto tabs = main_window.findChildren<QTabWidget*>();
  ASSERT_EQ(tabs.size(), 1);
  auto* button =
      qobject_cast<QToolButton*>(tabs[0]->cornerWidget(Qt::TopRightCorner));
  ASSERT_NE(button, nullptr);

  button->click();
  QApplication::processEvents();

  ASSERT_EQ(points.size(), 1u);
  // Below the button, not at the cursor: the menu hangs off the control that
  // opened it. Global coordinates, so only the relation to the button is
  // assertable without a shown window.
  EXPECT_EQ(points[0], button->mapToGlobal(QPoint{0, button->height()}));
}

// One button per strip, because a split makes a second strip and the mockup's
// `+` belongs to the strip it sits in
// (docs/product/ui-mockups/screens/shell-chrome.html).
TEST(ViewManagerQtComponentTest, EachTabStripCarriesItsOwnNewViewButton) {
  QMainWindow main_window;
  ViewManagerQtComponent component{main_window};
  component.SetNewTabHandler([](const QPoint&) {});

  auto* first_widget = new QWidget;
  auto* second_widget = new QWidget;
  auto first = MakeView(1, *first_widget, u"First");
  auto second = MakeView(2, *second_widget, u"Second");
  component.AddView(first, std::nullopt);
  component.AddView(second, first.id);
  component.SplitView(second.id, /*vertically=*/false);

  auto tabs = main_window.findChildren<QTabWidget*>();
  ASSERT_EQ(tabs.size(), 2);
  for (QTabWidget* strip : tabs) {
    EXPECT_NE(strip->cornerWidget(Qt::TopRightCorner), nullptr);
  }
}

// Pressing a strip's `+` calls the handler even when that strip's view is not
// the active one -- the button must not be gated on activation, which is
// machine state this process does not own (see the integration test's note).
TEST(ViewManagerQtComponentTest, NewViewButtonWorksInANonActiveStrip) {
  QMainWindow main_window;
  ViewManagerQtComponent component{main_window};

  int calls = 0;
  component.SetNewTabHandler([&](const QPoint&) { ++calls; });

  auto* first_widget = new QWidget;
  auto* second_widget = new QWidget;
  auto first = MakeView(1, *first_widget, u"First");
  auto second = MakeView(2, *second_widget, u"Second");
  component.AddView(first, std::nullopt);
  component.AddView(second, first.id);
  component.SplitView(second.id, /*vertically=*/false);

  auto tabs = main_window.findChildren<QTabWidget*>();
  ASSERT_EQ(tabs.size(), 2);
  for (QTabWidget* strip : tabs) {
    auto* button =
        qobject_cast<QToolButton*>(strip->cornerWidget(Qt::TopRightCorner));
    ASSERT_NE(button, nullptr);
    button->click();
  }
  QApplication::processEvents();

  EXPECT_EQ(calls, 2);
}
